/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.22.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;



#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE0305  // collection init can be simplified
#pragma warning disable IDE0034  // simplify default expression
#pragma warning disable IDE0066  // use switch expression
#pragma warning disable IDE0090  // simplify new expression
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Plugin.Thrift
{

  public partial class UserServiceLoginResponse : TBase
  {
    private int _errorCode;
    private string _errorMsg;

    public int ErrorCode
    {
      get
      {
        return _errorCode;
      }
      set
      {
        __isset.errorCode = true;
        this._errorCode = value;
      }
    }

    public string ErrorMsg
    {
      get
      {
        return _errorMsg;
      }
      set
      {
        __isset.errorMsg = true;
        this._errorMsg = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool errorCode;
      public bool errorMsg;
    }

    public UserServiceLoginResponse()
    {
    }

    public UserServiceLoginResponse DeepCopy()
    {
      var tmp5 = new UserServiceLoginResponse();
      if(__isset.errorCode)
      {
        tmp5.ErrorCode = this.ErrorCode;
      }
      tmp5.__isset.errorCode = this.__isset.errorCode;
      if((ErrorMsg != null) && __isset.errorMsg)
      {
        tmp5.ErrorMsg = this.ErrorMsg;
      }
      tmp5.__isset.errorMsg = this.__isset.errorMsg;
      return tmp5;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32)
              {
                ErrorCode = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                ErrorMsg = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp6 = new TStruct("UserServiceLoginResponse");
        await oprot.WriteStructBeginAsync(tmp6, cancellationToken);
        var tmp7 = new TField();
        if(__isset.errorCode)
        {
          tmp7.Name = "errorCode";
          tmp7.Type = TType.I32;
          tmp7.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
          await oprot.WriteI32Async(ErrorCode, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((ErrorMsg != null) && __isset.errorMsg)
        {
          tmp7.Name = "errorMsg";
          tmp7.Type = TType.String;
          tmp7.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp7, cancellationToken);
          await oprot.WriteStringAsync(ErrorMsg, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is UserServiceLoginResponse other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.errorCode == other.__isset.errorCode) && ((!__isset.errorCode) || (global::System.Object.Equals(ErrorCode, other.ErrorCode))))
        && ((__isset.errorMsg == other.__isset.errorMsg) && ((!__isset.errorMsg) || (global::System.Object.Equals(ErrorMsg, other.ErrorMsg))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if(__isset.errorCode)
        {
          hashcode = (hashcode * 397) + ErrorCode.GetHashCode();
        }
        if((ErrorMsg != null) && __isset.errorMsg)
        {
          hashcode = (hashcode * 397) + ErrorMsg.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp8 = new StringBuilder("UserServiceLoginResponse(");
      int tmp9 = 0;
      if(__isset.errorCode)
      {
        if(0 < tmp9++) { tmp8.Append(", "); }
        tmp8.Append("ErrorCode: ");
        ErrorCode.ToString(tmp8);
      }
      if((ErrorMsg != null) && __isset.errorMsg)
      {
        if(0 < tmp9++) { tmp8.Append(", "); }
        tmp8.Append("ErrorMsg: ");
        ErrorMsg.ToString(tmp8);
      }
      tmp8.Append(')');
      return tmp8.ToString();
    }
  }

}
