/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.22.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;



#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE0305  // collection init can be simplified
#pragma warning disable IDE0034  // simplify default expression
#pragma warning disable IDE0066  // use switch expression
#pragma warning disable IDE0090  // simplify new expression
#pragma warning disable IDE0290  // use primary CTOR
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Plugin.Thrift
{
  public partial class UserService
  {
    public interface IAsync
    {
      global::System.Threading.Tasks.Task<global::Plugin.Thrift.UserServiceLoginResponse> Login(global::Plugin.Thrift.UserServiceLoginRequest @request, CancellationToken cancellationToken = default);

    }


    public class Client : TBaseClient, IDisposable, IAsync
    {
      public Client(TProtocol protocol) : this(protocol, protocol)
      {
      }

      public Client(TProtocol inputProtocol, TProtocol outputProtocol) : base(inputProtocol, outputProtocol)
      {
      }

      public async global::System.Threading.Tasks.Task<global::Plugin.Thrift.UserServiceLoginResponse> Login(global::Plugin.Thrift.UserServiceLoginRequest @request, CancellationToken cancellationToken = default)
      {
        await send_Login(@request, cancellationToken);
        return await recv_Login(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task send_Login(global::Plugin.Thrift.UserServiceLoginRequest @request, CancellationToken cancellationToken = default)
      {
        await OutputProtocol.WriteMessageBeginAsync(new TMessage("Login", TMessageType.Call, SeqId), cancellationToken);
        
        var tmp10 = new InternalStructs.Login_args() {
          Request = @request,
        };
        
        await tmp10.WriteAsync(OutputProtocol, cancellationToken);
        await OutputProtocol.WriteMessageEndAsync(cancellationToken);
        await OutputProtocol.Transport.FlushAsync(cancellationToken);
      }

      public async global::System.Threading.Tasks.Task<global::Plugin.Thrift.UserServiceLoginResponse> recv_Login(CancellationToken cancellationToken = default)
      {
        
        var tmp11 = await InputProtocol.ReadMessageBeginAsync(cancellationToken);
        if (tmp11.Type == TMessageType.Exception)
        {
          var tmp12 = await TApplicationException.ReadAsync(InputProtocol, cancellationToken);
          await InputProtocol.ReadMessageEndAsync(cancellationToken);
          throw tmp12;
        }

        var tmp13 = new InternalStructs.Login_result();
        await tmp13.ReadAsync(InputProtocol, cancellationToken);
        await InputProtocol.ReadMessageEndAsync(cancellationToken);
        if (tmp13.__isset.success)
        {
          return tmp13.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "Login failed: unknown result");
      }

    }

    public class AsyncProcessor : ITAsyncProcessor
    {
      private readonly IAsync _iAsync;
      private readonly ILogger<AsyncProcessor> _logger;

      public AsyncProcessor(IAsync iAsync, ILogger<AsyncProcessor> logger = default)
      {
        _iAsync = iAsync ?? throw new ArgumentNullException(nameof(iAsync));
        _logger = logger;
        processMap_["Login"] = Login_ProcessAsync;
      }

      protected delegate global::System.Threading.Tasks.Task ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken);
      protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

      public async Task<bool> ProcessAsync(TProtocol iprot, TProtocol oprot)
      {
        return await ProcessAsync(iprot, oprot, CancellationToken.None);
      }

      public async Task<bool> ProcessAsync(TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken)
      {
        try
        {
          var msg = await iprot.ReadMessageBeginAsync(cancellationToken);

          processMap_.TryGetValue(msg.Name, out var fn);

          if (fn == null)
          {
            await TProtocolUtil.SkipAsync(iprot, TType.Struct, cancellationToken);
            await iprot.ReadMessageEndAsync(cancellationToken);
            var x = new TApplicationException (TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
            await oprot.WriteMessageBeginAsync(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID), cancellationToken);
            await x.WriteAsync(oprot, cancellationToken);
            await oprot.WriteMessageEndAsync(cancellationToken);
            await oprot.Transport.FlushAsync(cancellationToken);
            return true;
          }

          await fn(msg.SeqID, iprot, oprot, cancellationToken);

        }
        catch (IOException)
        {
          return false;
        }

        return true;
      }

      public async global::System.Threading.Tasks.Task Login_ProcessAsync(int seqid, TProtocol iprot, TProtocol oprot, CancellationToken cancellationToken)
      {
        var tmp14 = new InternalStructs.Login_args();
        await tmp14.ReadAsync(iprot, cancellationToken);
        await iprot.ReadMessageEndAsync(cancellationToken);
        var tmp15 = new InternalStructs.Login_result();
        try
        {
          tmp15.Success = await _iAsync.Login(tmp14.Request, cancellationToken);
          await oprot.WriteMessageBeginAsync(new TMessage("Login", TMessageType.Reply, seqid), cancellationToken); 
          await tmp15.WriteAsync(oprot, cancellationToken);
        }
        catch (TTransportException)
        {
          throw;
        }
        catch (Exception tmp16)
        {
          var tmp17 = $"Error occurred in {GetType().FullName}: {tmp16.Message}";
          if(_logger != null)
            _logger.LogError("{Exception}, {Message}", tmp16, tmp17);
          else
            Console.Error.WriteLine(tmp17);
          var tmp18 = new TApplicationException(TApplicationException.ExceptionType.InternalError," Internal error.");
          await oprot.WriteMessageBeginAsync(new TMessage("Login", TMessageType.Exception, seqid), cancellationToken);
          await tmp18.WriteAsync(oprot, cancellationToken);
        }
        await oprot.WriteMessageEndAsync(cancellationToken);
        await oprot.Transport.FlushAsync(cancellationToken);
      }

    }

    public class InternalStructs
    {

      public partial class Login_args : TBase
      {
        private global::Plugin.Thrift.UserServiceLoginRequest _request;

        public global::Plugin.Thrift.UserServiceLoginRequest Request
        {
          get
          {
            return _request;
          }
          set
          {
            __isset.@request = true;
            this._request = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool @request;
        }

        public Login_args()
        {
        }

        public Login_args DeepCopy()
        {
          var tmp19 = new Login_args();
          if((Request != null) && __isset.@request)
          {
            tmp19.Request = (global::Plugin.Thrift.UserServiceLoginRequest)this.Request.DeepCopy();
          }
          tmp19.__isset.@request = this.__isset.@request;
          return tmp19;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 1:
                  if (field.Type == TType.Struct)
                  {
                    Request = new global::Plugin.Thrift.UserServiceLoginRequest();
                    await Request.ReadAsync(iprot, cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp20 = new TStruct("Login_args");
            await oprot.WriteStructBeginAsync(tmp20, cancellationToken);
            var tmp21 = new TField();
            if((Request != null) && __isset.@request)
            {
              tmp21.Name = "request";
              tmp21.Type = TType.Struct;
              tmp21.ID = 1;
              await oprot.WriteFieldBeginAsync(tmp21, cancellationToken);
              await Request.WriteAsync(oprot, cancellationToken);
              await oprot.WriteFieldEndAsync(cancellationToken);
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is Login_args other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.@request == other.__isset.@request) && ((!__isset.@request) || (global::System.Object.Equals(Request, other.Request))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((Request != null) && __isset.@request)
            {
              hashcode = (hashcode * 397) + Request.GetHashCode();
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp22 = new StringBuilder("Login_args(");
          int tmp23 = 0;
          if((Request != null) && __isset.@request)
          {
            if(0 < tmp23++) { tmp22.Append(", "); }
            tmp22.Append("Request: ");
            Request.ToString(tmp22);
          }
          tmp22.Append(')');
          return tmp22.ToString();
        }
      }


      public partial class Login_result : TBase
      {
        private global::Plugin.Thrift.UserServiceLoginResponse _success;

        public global::Plugin.Thrift.UserServiceLoginResponse Success
        {
          get
          {
            return _success;
          }
          set
          {
            __isset.@success = true;
            this._success = value;
          }
        }


        public Isset __isset;
        public struct Isset
        {
          public bool @success;
        }

        public Login_result()
        {
        }

        public Login_result DeepCopy()
        {
          var tmp24 = new Login_result();
          if((Success != null) && __isset.@success)
          {
            tmp24.Success = (global::Plugin.Thrift.UserServiceLoginResponse)this.Success.DeepCopy();
          }
          tmp24.__isset.@success = this.__isset.@success;
          return tmp24;
        }

        public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
        {
          iprot.IncrementRecursionDepth();
          try
          {
            TField field;
            await iprot.ReadStructBeginAsync(cancellationToken);
            while (true)
            {
              field = await iprot.ReadFieldBeginAsync(cancellationToken);
              if (field.Type == TType.Stop)
              {
                break;
              }

              switch (field.ID)
              {
                case 0:
                  if (field.Type == TType.Struct)
                  {
                    Success = new global::Plugin.Thrift.UserServiceLoginResponse();
                    await Success.ReadAsync(iprot, cancellationToken);
                  }
                  else
                  {
                    await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  }
                  break;
                default: 
                  await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
                  break;
              }

              await iprot.ReadFieldEndAsync(cancellationToken);
            }

            await iprot.ReadStructEndAsync(cancellationToken);
          }
          finally
          {
            iprot.DecrementRecursionDepth();
          }
        }

        public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
        {
          oprot.IncrementRecursionDepth();
          try
          {
            var tmp25 = new TStruct("Login_result");
            await oprot.WriteStructBeginAsync(tmp25, cancellationToken);
            var tmp26 = new TField();

            if(this.__isset.@success)
            {
              if (Success != null)
              {
                tmp26.Name = "Success";
                tmp26.Type = TType.Struct;
                tmp26.ID = 0;
                await oprot.WriteFieldBeginAsync(tmp26, cancellationToken);
                await Success.WriteAsync(oprot, cancellationToken);
                await oprot.WriteFieldEndAsync(cancellationToken);
              }
            }
            await oprot.WriteFieldStopAsync(cancellationToken);
            await oprot.WriteStructEndAsync(cancellationToken);
          }
          finally
          {
            oprot.DecrementRecursionDepth();
          }
        }

        public override bool Equals(object that)
        {
          if (!(that is Login_result other)) return false;
          if (ReferenceEquals(this, other)) return true;
          return ((__isset.@success == other.__isset.@success) && ((!__isset.@success) || (global::System.Object.Equals(Success, other.Success))));
        }

        public override int GetHashCode() {
          int hashcode = 157;
          unchecked {
            if((Success != null) && __isset.@success)
            {
              hashcode = (hashcode * 397) + Success.GetHashCode();
            }
          }
          return hashcode;
        }

        public override string ToString()
        {
          var tmp27 = new StringBuilder("Login_result(");
          int tmp28 = 0;
          if((Success != null) && __isset.@success)
          {
            if(0 < tmp28++) { tmp27.Append(", "); }
            tmp27.Append("Success: ");
            Success.ToString(tmp27);
          }
          tmp27.Append(')');
          return tmp27.ToString();
        }
      }

    }

  }
}
